# Autogenerated wrapper script for libaio_jll for i686-linux-musl
export libaio

JLLWrappers.@generate_wrapper_header("libaio")
JLLWrappers.@declare_library_product(libaio, "libaio.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaio,
        "lib/libaio.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
